// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBe2V-ZR4B__59jDg-heergvVo3ND7u_E',
    appId: '1:334597347536:web:e0e4dec62e32d77ad666d5',
    messagingSenderId: '334597347536',
    projectId: 'fit-flow-9b05e',
    authDomain: 'fit-flow-9b05e.firebaseapp.com',
    storageBucket: 'fit-flow-9b05e.firebasestorage.app',
    measurementId: 'G-2SHZWMESNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlVwaWFO-5lGQYeA6YNIlWYJD1AAAC-k',
    appId: '1:334597347536:android:b67625e4a887d353d666d5',
    messagingSenderId: '334597347536',
    projectId: 'fit-flow-9b05e',
    storageBucket: 'fit-flow-9b05e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahI_lH_vdhtjcraLi-ngDqsjzyU--8bw',
    appId: '1:334597347536:ios:07af6637512713bbd666d5',
    messagingSenderId: '334597347536',
    projectId: 'fit-flow-9b05e',
    storageBucket: 'fit-flow-9b05e.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBahI_lH_vdhtjcraLi-ngDqsjzyU--8bw',
    appId: '1:334597347536:ios:07af6637512713bbd666d5',
    messagingSenderId: '334597347536',
    projectId: 'fit-flow-9b05e',
    storageBucket: 'fit-flow-9b05e.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBe2V-ZR4B__59jDg-heergvVo3ND7u_E',
    appId: '1:334597347536:web:7ac168337355509ad666d5',
    messagingSenderId: '334597347536',
    projectId: 'fit-flow-9b05e',
    authDomain: 'fit-flow-9b05e.firebaseapp.com',
    storageBucket: 'fit-flow-9b05e.firebasestorage.app',
    measurementId: 'G-FNQ5SHLCKS',
  );
}
